apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: david
spec:
  replicas: 2
  selector:
    matchLabels:
      app: david
  template:
    metadata:
      labels:
        app: david
    spec:
      containers:
      - name: hippo
        image: antonydavid96/tomcat-application:1
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demoservice
spec:
  type: NodePort
  selector:
    app: david
  ports:
    - port: 80
      targetPort: 8085
      nodePort: 30750